Screen('Preference','SkipSyncTests',0);
rInit({'screenMode','local','showWarnings',true});

dotsIdx         = rAdd( ...
    'dXdots',   1, ...
    'color',    [255 255 255], ...
    'direction',0, ...
    'coherence',25, ...
    'diameter', 1, ...
    'size',     8, ...
    'loops',    1, ...
    'density',  20, ...
    'speed',    7, ...
    'lifetimeMode', 'random', ...
    'visible',  true, ...
    'debugSavePts', true ...
);

a = rGraphicsDraw(1);

rDone;

x = -1:0.01:1;
y = sqrt(1-x.^2);

x = (x+1)/2;
y = (y+1)/2;

figure(1);
scatter(x,y);
hold on;
scatter(x,-y+1);

scatter(a(1,1,:),a(2,1,:))
