Screen('Preference','SkipSyncTests',0);
rInit({'screenMode','local','showWarnings',true});

dotsIdx         = rAdd( ...
    'dXdots',   1, ...
    'color',    [255 255 255], ...
    'direction',0, ...
    'coherence',25, ...
    'diameter', 10, ...
    'size',     8, ...
    'loops',    1, ...
    'density',  20, ...
    'speed',    7, ...
    'lifetimeMode', 'random', ...
    'visible',  true, ...
    'debugSavePts', true ...
);

a = rGraphicsDraw(3000);
